version: '3.9'

services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    env_file:
      - ./.env

  app:
    depends_on:
      - db
    build: .
    restart: on-failure:1s
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db